server {
    listen 80;
    server_name api.edizo.in; # Temporary test domain

    root /home/server/arun; # Path where you extracted the files
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    # Optimization: Cache static assets
    location /assets/ {
        expires 1y;
        add_header Cache-Control "public, immutable";
    }

    # Enable Gzip compression
    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
}
